spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    #开发时关闭缓存,不然没法看到实时页面
    # Allow Thymeleaf templates to be reloaded at dev time
    cache: false
server:
  port: 8091
logging:
  file: /var/log/2019mcrm.log
  level: INFO
file:
  name: /home/2019mcrm.xlsx
  #name: /Users/tab.ren/Downloads/test.xlsx
#  name: /home/tab/Downloads/2019年巡检清单（各厂家合表2.xlsx
  sheets: 0
  serverSn:
    index: 7
  projectorSn:
    index: 7
cell:
  name: 影院名称,省,市,院线名称,专资编码,厅号,放映机型号,放映机序列号,影院地址,影院经理,机务经理,财务经理,法人代表
  show:
    server: 0,3,5,6,7,8,9,10
    projector: 0,3,5,6,7,8,9,10
