spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    #开发时关闭缓存,不然没法看到实时页面
    # Allow Thymeleaf templates to be reloaded at dev time
    cache: false
server:
  port: 9009
logging:
  file: /var/log/mcrm.log
  level: trace
file:
  name: /home/tab/Downloads/test.xlsx
  #name: /home/tab/Downloads/hspociksjnp.xlsx
  #name: /Users/tab.ren/Downloads/test.xlsx
  serverSn:
    index: 16
  projectorSn:
    index: 14
cell:
  show:
    server: 0,8,10,11,15,16,19,21
    projector: 0,8,10,11,13,14,19,20
